cuter-testing/cuter

- Makefile.in
- cuter
- src/cuter.erl
- src/cuter_codeserver.erl
- src/cuter_eval.erl
- src/cuter_mock.erl
- src/cuter_pp.erl
- test/ftest/expected/whitelist-f-1.expected
- test/ftest/src/whitelist.erl
- test/ftest/whitelist/whitelist-f-1.txt
- test/functional_test
- test/utest/src/cuter_codeserver_tests.erl
- test/utest/src/cuter_eval_tests.erl
- test/utest/src/cuter_iserver_tests.erl
The user can supply a file with exported MFAs that will be whitelisted and will be treated as BIFs.
> Fix mfa whitelisting

- src/cuter_mock.erl
- test/ftest/expected/whitelist-g-1.expected
- test/ftest/src/whitelist.erl
- test/ftest/whitelist/whitelist-g-1.txt
- test/functional_test
The user can whitelist batch of MFAs with
- `{M, F, '*'}`:   `M:F` of any arity.
- `{M, '*', '*'}`:  Any function in module `M`.
> Mfa whitelisting with wildcards

- src/cuter_analyzer.erl
- src/cuter_callgraph.erl
- src/cuter_codeserver.erl
The only case that CutEr would try to load the abstract code of
a whitelisted module is when it would try to calculate the callgraph.
This is now fixed as CutEr will ignore such MFAs.
> Do not try to load the abstract code of whitelisted modules

- src/cuter_types.erl
The existence of unsupported types inlined in specs no longer causes the spec parser to fail.
This fixes issue #10.
> Fixes issue #10

- src/cuter_json.erl
- test/utest/src/cuter_json_tests.erl
Fix encoding of terms containing bitstrings and add a unit test.
Previously, terms that have bitstrings as subterms would not be JSON encoded.
In these cases, no log entry was created and the trace file was incomplete; causing runtime errors during solving.
In the case of issue #16, the particular term was 
```erlang
[<<"false">>]
```
and the command that was to be logged was
```
$18 = [ $17 | [<<"false">>] ]
```
where `$17` and `$18` are symbolic variables.
> Fix issue #16

- Makefile.in
- priv/cuter_io.py
- priv/cuter_print.py
- priv/cuter_solve_offline.py
- test/python_test
- test/utest/src/cuter_tests_lib.erl
I have added `cuter_solve_offline.py` in `priv` directory.
It is used to load a trace file and invoke the solver to reverse a specific constraint.
For example
```
aggelgian@lambda:~/git-repos/cuter$ ./priv/cuter_solve_offline.py temp/execexec4/run.trace 3 
Solving the model ... sat
[x1 = atm(acons(116, acons(114, acons(117, acons(101, anil)))))]
```
It also prints the commands in the trace file when the option `--print-constraints` is passed.
This pull request implements feature #18.
> Add a Python script to solve constraints in trace files offline

- cuter
- test/ftest/expected/collection-f1-1.expected
- test/ftest/src/collection.erl
- test/functional_test
The user can append Dir1, Dir2, etc to the code path when invoking
the cuter script by running
```
cuter Mod Fun '[Arg1, Arg2, ..., ArgN]' -a Dir1:Dir2:..:DirN
```
or
```
cuter Mod Fun '[Arg1, Arg2, ..., ArgN]' --append-path=Dir1:Dir2:..:DirN
```
This pull request implements the feature #14.
> Add a command line option to append directories to code path

- priv/cuter_z3.py
Every time the solver encounters a PID or a reference while loading a trace file, it will replace them with a default term, namely `42`.
This approximation is performed as the above types are not supported in the solver's logic.
This fixes issue #25.
> Replace PIDs & references with a default value during trace loading #25

- cuter
- test/functional_test
Also remove the -l option.
CutEr now first tries to find the module in the code path.
This check is bypassed with the -r option.
If the module is non existent, then it tries to compile it.
This pull request closes issues #24 and #31.
> Replace getopt module with argparse

- Makefile.in
- priv/cuter_port.py
- priv/cuter_representation.py
- priv/cuter_z3.py
- src/cuter_json.erl
- test/utest/src/cuter_json_tests.erl
Extend the term encoding in Z3 with funs.
Retrieve the representation of a fun from a satisfiable model and successfully encode it as a JSON string.
Add some unit tests for this mechanism.
This impements feature #34.
> Extend term encoding in Z3 to include funs

- src/cuter_erlang.erl
- src/cuter_mock.erl
- test/ftest/expected/bitstr-bit_sz-1.expected
- test/ftest/expected/bitstr-byte_sz-1.expected
- test/ftest/src/bitstr.erl
- test/functional_test
- test/utest/src/cuter_erlang_tests.erl
Support the BIFs `erlang:bit_size/1` and `erlang:byte_size/1`.
This pull request implements #64.
> Support bit_size/1 & byte_size/1

- src/cuter_erlang.erl
- test/ftest/src/collection.erl
- test/ftests.json
Minor fix.
Function cuter_erlang:list_to_integer/1 was taking strings "-" and "+" without an integer as valid inputs.
The test was also wrong.
> Fix issue #82

- src/cuter_erlang.erl
- test/ftest/src/collection.erl
- test/ftests.json
Make it a total function (as it should be) and allow
it to enter the manual calculation of whether a bitstring
is a binary only if it is actually a bitstring.
This pull request fixes #86.
> Fix the overriding mfa of is_binary/1

- .travis.yml
Download Z3 binaries instead of compiling it for TravisCI builds.
This PR implements #89.
> Use Z3 4.4.1 binaries in TravisCI build

- Makefile.in
- include/cuter_types.hrl
- priv/cuter_common.py
- priv/cuter_smt.py
- src/cuter_codeserver.erl
- src/cuter_pp.erl
- src/cuter_proto_spec.proto
- src/cuter_serial.erl
- src/cuter_types.erl
- test/ftest/src/collection.erl
- test/ftests.json
- test/functional_test
- test/utest/src/cuter_codeserver_tests.erl
- test/utest/src/cuter_iserver_tests.erl
- test/utest/src/cuter_serial_tests.erl
This PR will allow CutEr to reason over recursive types.
Remaining tasks:
> Support Recursive types

- cuter
- src/cuter.erl
- src/cuter_codeserver.erl
- src/cuter_types.erl
- test/ftest/src/collection.erl
- test/ftests.json
- test/utest/src/cuter_codeserver_tests.erl
- test/utest/src/cuter_eval_tests.erl
- test/utest/src/cuter_iserver_tests.erl
The point of this MR is to normalize function specifications and type definitions to facilitate SMT solving.
This works well with intricate specs, like `complex_spec:f/1`, but leads to timeouts in some cases, like `collection:fclist/1`.
So I've added a flag to disable this optimization, if needed.
> Normalize Types

- src/cuter_serial.erl
- test/utest/src/cuter_serial_tests.erl
Also comment out the corresponding tests until we decide what
is the proper way to handle these terms in the solver.
This fixes the SOLVER ERROR crash reported in #120.
> Comment out encoding of refs and pids for the time being

- src/cuter_eval.erl
- test/ftest/src/bitstr.erl
- test/ftests.json
Branching points on size and type of segments
Try to generate inputs that will cause bitstring construction or
matching to fail due to
- Negative sizes in segment size.
- Incompatible arguments with respect to the type expected by the
segment.
> Add constraints on encoding flags of bitstrings

- test/utest/src/cuter_tests.erl
This change, done to avoid some timeouts we were experiencing while
running the test suite at some point, was the only difference of
branch new-z3 that I could see.
See also the discussion on commit https://github.com/cuter-testing/cuter/commit/1510a049227e545db9521974aa92ce369c041fa6.
> Turn an Eunit test into a test generator

- priv/cuter_smt.py
- test/ftest/src/funs.erl
- test/ftests.json
The pointwise definition of a function in the solver's logic allows a
function to have an empty domain set, which results in a total function
with an undefined value.
Forcing all functions to be defined for at least one point ensures that
there are no undefined values in the codomain.
> Force function domains to contain at least one element

- src/cuter_lib.erl
- src/cuter_pp.erl
- test/ftest/src/funs.erl
- test/ftests.json
- test/functional_test
- test/terms.py
e.g.
```
aggelgian@...:~/cuter$ ./cuter -r -v -p 2 -s 8 f2 mainfun '[fun(F) when is_function(F, 1) -> 42 end]'
Compiling f2.erl ... ok
Testing f2:mainfun/1 ...
f2:mainfun/1
Spec:
fun((fun((fun((integer()) -> integer())) -> integer())) -> ok)
Types:
WARNING: Encountered an unsupported type while parsing the types in Core Erlang forms!
Form: {type,608,map,any}
f2:mainfun(#Fun<erl_eval.6.128620087>) ... ok
xxxxxxxxxx
f2:mainfun(fun(_) -> 321 end) ... ok
xxxxxxxxx
A = fun(_) -> 7 end, f2:mainfun(fun(A) -> 654; (_) -> 321 end) ... ok
x
Solver Statistics ...
- Solved models   : 2
- Unsolved models : 20
No Runtime Errors Occured
```
> Move funs in arguments to separate variables to avoid illegal patterns.

- .gitignore
- cuter
- priv/cuter_global.py
- priv/cuter_interface.py
- priv/cuter_logger.py
- priv/cuter_smt_process.py
- src/cuter.erl
Enable to store the SMT model that is sent for validation to the solver.
- Each invocation creates a separate log file, named smt.log.XXXXX,
in the current working directory.
- Guard this feature behind a flag ("-ds", "--debug_smt").
> Store SMT invocations for debugging.

- priv/cuter_port.py
- src/cuter_proto_solver_command.proto
- src/cuter_serial.erl
- src/cuter_solver.erl
If the entry point has arity > 1, and the solve returns unknown or
timeout for a model, we would try to fix some of the variables to
specific values to simplify the model.
This functionality is not helpful in our case. If the solver reponds
with unknown or times out, then there is a regression in the solver or
in our tool.
> Do not attempt to fix variables to specific values

- Makefile.in
- cuter
- include/cuter_macros.hrl
- src/cuter.erl
- src/cuter_analyzer.erl
- src/cuter_codeserver.erl
- src/cuter_config.erl
- src/cuter_lib.erl
- src/cuter_pp.erl
- src/cuter_scheduler.erl
- src/cuter_types.erl
- test/ftests.json
- test/utest/src/cuter_codeserver_tests.erl
- test/utest/src/cuter_config_tests.erl
- test/utest/src/cuter_eval_tests.erl
- test/utest/src/cuter_iserver_tests.erl
- test/utest/src/cuter_solver_tests.erl
Move configuration to a globally accessible process.
Passing parameters around does not scale. Also, macros do not allow the user to override them at runtime.
Also, consider the runtime options as proplists.
> Make configuration globally accessible

- src/cuter_callgraph.erl
- src/cuter_eval.erl
- src/cuter_mock.erl
Before the MFA would both override some MFAs and decide which MFAs are
BIFs.
These are now two separate functions, that make more sense semantically.
> Split cuter_mock:simulate_behaviour/3

- src/cuter_cerl.erl
- src/cuter_codeserver.erl
- src/cuter_eval.erl
- test/utest/src/cuter_cerl_tests.erl
The intention is to make consumers of code unaware of how it is stored
in CutEr.
Each MFA will be an opaque kfun() and each module will be an opaque
kmodule(), the module cache will be a collection of kmodules() etc, and we will provide an API to access and modify them.
> Abstract the code & metadata of an MFA as a kfun().

- include/cuter_types.hrl
- priv/cuter_common.py
- priv/cuter_print.py
- priv/cuter_smt.py
- src/cuter_pp.erl
- src/cuter_proto_spec.proto
- src/cuter_serial.erl
- src/cuter_types.erl
- test/utest/src/cuter_types_tests.erl
- test/utest/src/types_and_specs.erl
References #183 
Add support for Erlang map type definitions in function specs.
- Add new ?map_tag macro definition
- Introduce Spec.{Association, AssociationList} messages
- Introduce 'MAP' value for Spec.Type enum
- Add new cuter_type t_map/0 and t_map/1
- Support map type in t_from_form
- Encode map specs and send to Python
- Add TODO for how the smt library can handle maps (will be added later)
- Add unit tests for parsing specs containing map types
- Support pretty printing map specs.
- We do keep track of mandatory vs optional type associations for the map. 
- I have attempted to follow existing local code conventions as much as possible.
- Cuter still does not work well with map types (in fact, it still crashes when a map expression is found), but can now properly recognise map …
> Support spec definitions with Erlang maps (183)

- Makefile.in
- src/cuter_cerl.erl
- src/cuter_codeserver.erl
- src/cuter_eval.erl
- test/utest/include/types.hrl
- test/utest/src/cuter_cerl_tests.erl
- test/utest/src/cuter_codeserver_tests.erl
Starting off with an implementation of
`  kmodule() :: ets:tid()`
for compatibility with the current code, but will change to
`  kmodule() :: #{ ... }`
in a follow-up PR.
> Abstract the code of a module as a kmodule().

- requirements.txt
When using Python 3.9 (of current Debian stable) one of the unit tests fails due to requiring a newer version of mypy.
> Upgrade mypy version (for python 3.9)

- Makefile.in
- priv/cuter_common.py
- priv/cuter_print.py
- priv/cuter_smt.py
- src/cuter_serial.erl
- test/ftest/src/pingpong.erl
- test/ftests.json
Currently, we were dropping log entries with PIDs and refs, which led to missing critical information for certain programs:
- when a process would send a message like `{self(), 42}`
- when a process would consume a message from the mailbox
The solver does not need to reason about these types, but just "tolerate" them. We do not expect that they will be passed as arguments to the unit under test, but they are being generated as values during the execution of the program.
> Record PIDs and refs in log traces

- configure.ac
The check we had for the Python3 version was broken. It performed string comparison, so "3.11.2" was considered smaller than "3.6" and configure failed.  Fix this by properly parsing the version and properly comparing against version 3.6.
> Fix the check for Python version
