cuter-testing/cuter

- Makefile.in
- cuter
- include/cuter_macros.hrl
- priv/cuter_common.py
- src/cuter.erl
- src/cuter_analyzer.erl
- src/cuter_callgraph.erl
- src/cuter_cerl.erl
- src/cuter_codeserver.erl
- src/cuter_erlang.erl
- src/cuter_eval.erl
- src/cuter_log.erl
- src/cuter_mock.erl
- src/cuter_pp.erl
- src/cuter_scheduler_maxcover.erl
- src/cuter_symbolic.erl
- test/utest/src/cuter_cerl_tests.erl
- test/utest/src/cuter_solver_tests.erl
- Calculate the CFG.
- Calculate some measures of coverage.
- Show statistics of models solved / not solved.
> Calculate coverage

- .travis.yml
- Makefile.in
- TODO.md
- src/cuter_codeserver.erl
- src/cuter_pp.erl
- src/cuter_types.erl
- test/eunit_test
- test/ftest/expected/collection-f-1.expected
- test/ftest/src/collection.erl
- test/ftest/src/complex_spec.erl
- test/functional_test
- test/python_test
- test/utest/src/cuter_codeserver_tests.erl
- test/utest/src/cuter_tests_lib.erl
- test/utest/src/cuter_types_tests.erl
- test/utest/src/types_and_specs.erl
- test/utest/src/types_and_specs2.erl
Still missing:
- Recursive types.
- A `pa` flag to include beam files to the path.
> Support remote types

- cuter
- src/cuter.erl
- src/cuter_pp.erl
- src/cuter_types.erl
- test/ftest/expected/bitstr-f26-2.expected
- test/ftest/expected/collection-g-1.expected
- test/ftest/src/collection.erl
- test/functional_test
This pull request fully fixes issue #10.
It seems that the previous pull request #11 only partially fixed the problem.
> Properly fix issue #10 & add a functional test for it

- priv/cuter_types.py
- test/ftest/expected/collection-g1-1.expected
- test/ftest/src/collection.erl
- test/functional_test
> Fix typos in cuter_types.py and fix issue #13

- Makefile.in
- src/cuter_pp.erl
- test/ftest/expected/funs-f1-1.expected
- test/ftest/expected/funs-f2-3.expected
- test/ftest/expected/funs-f3-3.expected
- test/ftest/expected/funs-f41-3.expected
- test/ftest/expected/funs-f42-3.expected
- test/ftest/expected/funs-f5-4.expected
- test/ftest/expected/funs-f6-1.expected
- test/ftest/expected/funs-f7-2.expected
- test/ftest/expected/funs-f8-2.expected
- test/ftest/expected/funs-f91-3.expected
- test/ftest/expected/funs-f92-2.expected
- test/utest/src/cuter_pp_tests.erl
This pull request implements feature #37.
> Pretty print funs

- Makefile.in
- cuter
- test/ftest/expected/sum-classify-1.expected
- test/ftest/src/sum.erl
- test/functional_test
This pull request implements #48.
> Pass include paths in compilation via script

- Makefile.in
- test/ftest/expected/funs-f14-2.expected
- test/ftest/src/funs.erl
- test/functional_test
Also allow test functions to not have spec.
> Add a test to accompany 6a3b9f2

- src/cuter_mock.erl
- test/ftest/expected/collection-eval_nif-1.expected
- test/ftest/src/collection.erl
- test/functional_test
Evaluate NIFs concretely.
This pull request fixes #65.
> Evaluate NIFs concretely #65

- .travis.yml
Unfortunately, 18.3 is not yet available
> Update the Erlang releases used by Travis to be the last 17.x

- .gitignore
- README.md
- priv/cuter_generic_solver.py
- priv/cuter_global.py
- priv/cuter_interface.py
- priv/cuter_io.py
- priv/cuter_port.py
- priv/cuter_representation.py
- priv/cuter_smt.py
- priv/cuter_solve_offline.py
- priv/cuter_types.py
- priv/cuter_z3.py
- src/cuter.erl
- src/cuter_poller.erl
- test/functional_test
> Prepare the Python backend for multiple solvers

- .travis.yml
- Makefile.in
- README.md
- test/ftest/src/funs.erl
- test/ftests.json
- test/functional_test
- test/terms.py
A set of properties are defined for each test case. They are Python expressions that evaluate to boolean values where placeholders are used for the positional parameters of the function, like 
```
$1 == 42 and len($2) == 1 and $3 >> $4 == 2
```
After the execution of each test case, the inputs reported by CutEr are gathered and each one is tried against each defined property. The positional parameters are replaced and the expression is evaluated. The execution is considered successful if
1. Each input satisfies at least one property.
2. All the properties are covered.
This PR will address issue #94.
> Validate functional tests using properties for the inputs

- test/ftest/src/collection.erl
- test/ftest/src/funs.erl
- test/ftests.json
- test/functional_test
> Add missing testcases for BIF translation

- src/cuter_cerl.erl
- src/cuter_types.erl
- test/ftest/src/collection.erl
- test/ftests.json
> Fix parsing of record definitions

- src/cuter_symbolic.erl
- test/ftest/src/bitstr.erl
- test/ftests.json
> Fix exceptions from negative bitstring sizes in pattern matching

- src/cuter.erl
- src/cuter_callgraph.erl
- src/cuter_codeserver.erl
- src/cuter_pp.erl
- src/cuter_scheduler_maxcover.erl
- test/utest/src/cuter_tests.erl
This PR adds the ability to run CutEr on multiple units in once execution.
Create a file with the desired units.
```bash
$ cat multiple.txt 
{erl_internal, arith_op, [ ok, 1 ], 100}.
{erl_internal, bif, [ send, 2 ], 100}.
```
Run CutEr.
```bash
$ erl -noshell -pa ebin -eval "cuter:run_from_file(\"multiple.txt\", [{number_of_pollers,2},{number_of_solvers,2}])" -s init stop
Testing erl_internal:arith_op/2 ...
.........x...xxx.x.xx..xx..xx..xx..xx..xx..xxx.xxxxxx
Testing erl_internal:bif/2 ...
.......x.x...xx..xxx...x.x.x.x.xx..x.x.x...x.x...x.x.xx..xxx.x.x.x.x.x.x...x.x.x.x.xx..x.x.x...xxx...x...x...xx..xxx...xx..x...x.x...x...x.x...xxx...xx..x.x...xx..x.x.x.xx..xxx.x.x.x.x.x.x.x.x.x.x.x.x.x.x..xx...x.x.x..xxx..xx..xx..xx..xx..xx..xx..x.x.x...xxx.x.x.x.x.x.x..xx.x.x...x.x.x.x.xx..xx..xx..xx. …
```
> Run multiple units in one run

- .gitmodules
- .travis.yml
- README.md
- configure.ac
- test/utest/src/cuter_monitor_tests.erl
> Remove meck

- Makefile.in
> Remove meck references from Makefile

- .travis.yml
- Makefile.in
- configure.ac
- include/eunit_config.hrl
- src/cuter_eval.erl
- src/cuter_solver.erl
> Support the latest erlang versions

- priv/cuter_representation.py
Check the the functions in the Python unit test have the required properties instead of asserting for the exact representation. This will make the tests compatible with future Z3 versions.
> Test for correct behaviour in Python unit tests

- cuter
- test/eunit_test
Signed-off-by: Asaf Rachmani <asaf.rachmani@gmail.com>
> Support python3

- cuter
> Use halt/0 instead of init:stop/0 to terminate

- src/cuter.erl
- src/cuter_callgraph.erl
- src/cuter_pp.erl
app lifecycle:
- generate the app state
- run initializations
- start the app
- stop the app
> Clarify the app lifecycle

- Makefile.in
- configure.ac
Closes #181, using the proposed solution.
Please let me know if an alternative solution is preferred.
> Fix makefile when using a Python virtual environment

- .github/workflows/ci.yml
- README.md
- fetch_protoc.sh
- requirements.txt
This version is the latest 3.x.y and also fixes a security update.
Closes #194
> Update protobuf to version 3.20.2
